export const fabricTypeFilters = {
    ALL: 'All',
    ACRYLIC: 'Acrylic',
    COTTON_BLEND: 'Cotton Blend',
    COTTON_LINEN: 'Cotton Linen',
    JUTE_COTTON: 'Jute Cotton',
    JUTE_SILK: 'Jute Silk',
    LINEN: 'Linen',
    POLYCOTTON: 'Polycotton',
    POLYESTER: 'Polyester',
    POLYRAYON: 'Polyrayon',
    POLYVISCOSE: 'Polyviscose',
    PURE_COTTON: 'Pure Cotton',
    PURE_SILK: 'Pure Silk',
    PURE_WOOL: 'Pure Wool',
    SILK_BLEND: 'Silk Blend',
    SUEDE: 'Suede',
    VISCOSE_RAYON: 'Viscose Rayon',
    WOOL_BLEND: 'Wool Blend',
    CREPE: 'Crepe',
    POLY_CREPE: 'Poly Crepe',
    SATIN: 'Satin',
    GEORGETTE: 'Georgette',
    VISCOSE_SILK: 'Viscose Silk'
}


export const priceRangeFilters = {
    ALL: 'All',
    LESS_THAN_1500: "Less than Rs.1500",
    BETWEEN_1500_TO_2999: "Rs.1500 - Rs.2999",
    BETWEEN_3000_TO_4999: "Rs.3000 - Rs.4999",
    MORE_THAN_4999: "More than Rs.4999"
}

export const fabricColorFilters = {
    ALL: 'All',
    BLUE: 'Blue',
    BLACK: 'Black',
    NAVY_BLUE: 'Navy Blue',
    BEIGE: 'Beige',
    MAROON: 'Maroon',
    GREEN: 'Green',
    GREY: 'Grey',
    BROWN: 'Brown',
    YELLOW: 'Yellow',
    PINK: 'Pink',
    RED: 'Red',
    ORANGE: 'Orange',
    CREAM: 'Cream',
    WHITE: 'White',
    MULTI: 'Multi',
    PEACH: 'Peach',
    GOLD: 'Gold',
    MUSTARD: 'Mustard',
    OFF_WHITE: 'Off white',
    PURPLE: 'Purple',
    TEAL: 'Teal',
    CHARCOAL: 'Charcoal',
    TURQUOISE_BLUE: 'Turquoise Blue',
    RUST: 'Rust',
    OLIVE: 'Olive',
    SEA_GREEN: 'Sea Green',
    SILVER: 'Silver',
    KHAKI: 'Khaki',
    COFFEE_BROWN: 'Coffee Brown',
    CORAL: 'Coral',
    LIME_GREEN: 'Lime Green',
    BURGUNDY: 'Burgundy',
    MAGENTA: 'Magenta',
    COPPER: 'Copper',
    TAUPE: 'Taupe',
    GREY_MELANGE: 'Grey Melange',
    LAVENDER: 'Lavender',
    TAN: 'Tan',
    NUDE: 'Nude',
    MAUVE: 'Mauve',
}

export const fabricPatternFilters = {
    ALL: 'All',
    CHECKED: 'Checked',
    EMBROIDERED: 'Embroidered',
    SOLID: 'Solid',
    STRIPED: 'Striped',
    PRINTED: 'Printed',
    WOVEN_DESIGN: 'Woven Design'
}