export const pageTitles = {
    HOME: "Tailor-Made Men's Wear : Shop for Suit, Blazer, Tuxedo, Sherwani, Jodhpuri, Nehru Jacket, Kurta and more",
    SHERWANI: "Sherwani : Buy Tailor-Made Sherwani at Comfort of your Home",
    JODHPURI: "Jodhpuri Suit : Buy Tailor-Made Jodhpuri Suit at Comfort of your Home",
    NEHRU_JACKET: "Nehru Jacket : Buy Tailor-Made Nehru Jacket at Comfort of your Home",
    KURTA: "Kurta : Buy Tailor-Made Kurta at Comfort of your Home",
    TWO_PIECE_SUIT: "Two Piece Suit : Buy Tailor-Made Two Piece Suit at Comfort of your Home",
    THREE_PIECE_SUIT: "Three Piece Suit : Buy Tailor-Made Three Piece Suit at Comfort of your Home",
    CASUAL_BLAZER: "Casual Blazer : Buy Tailor-Made Casual Blazer at Comfort of your Home",
    TUXEDO: "Tuxedo : Buy Tailor-Made Tuxedo at Comfort of your Home",
    TROUSER: "Trouser : Buy Tailor-Made Trouser at Comfort of your Home",
    SHIRT: "Shirt : Buy Tailor-Made Shirt at Comfort of your Home",
    FESTIVES: "Buy Tailor-Made Festive Wear at Comfort of your Home",
    REGULAR: "Buy Tailor-Made Regular Wear at Comfort of your Home",
    HALDI: "Buy Tailor-Made Kurta for Haldi only at Righter",
    MEHENDI: "Buy Tailor-Made Kurta for Mehendi only at Righter",
    ENGAGEMENT: "Buy Tailor-Made Outfit for Engagement only at Righter",
    WEDDING: "Buy Tailor-Made Outfit for Your Wedding only at Righter",
    PRIVACY_POLICY: "Righter - Privacy Policy | Tailor-Made Men's Wear at Home",
    CUSTOMER_SUPPORT: "Righter - 24*7 available Customer Support | Tailor-Made Men's Wear at Home",
    TERMS_AND_CONDITIONS: "Righter - Terms & Conditions | Tailor-Made Men's Wear at Home",
    ABOUT_US: "About Righter | Tailor-Made Men's Wear at Home",
    FAQS: "Righter - Frequently Asked Questions | Tailor-Made Men's Wear at Home",
    RESIZE_AND_RETURN_POLICY: "Righter - Return & Resize Policy | Tailor-Made Men's Wear at Home",
    SHIPPING_POLICY: 'Righter - Shipping Policy | Tailor-Made Men\'s Wear at Home',
    PAYMENT_POLICY: 'Righter - Payment Policy | Tailor-Made Men\'s Wear at Home',
    GET_STARTED: 'Start Shopping with Righter | Tailor-Made Men\'s Wear at Home',
    BLOGS: "Righter - Blogs | Tailor-Made Men's Wear at Home",
    BLOGS_ONE: "/blogs/why-online-cloth-purchasing-has-the-slowest-adoption-across-the-categories",
    BLOGS_TWO: "/blogs/is-the-big-indian-wedding-market-rip-enough-for-a-big-shift",
    BLOGS_THREE: "/blogs/oyo-of-apparel-industry",
    BLOGS_FOUR: "/blogs/an-open-letter-to-a-to-be-groom",
    BLOGS_FIVE: "/blogs/how-i-choose-my-outfit-for-the-wedding-event-of-my-friend",
    BLOGS_SIX: "/blogs/best-places-to-do-wedding-shopping-for-men-in-bangalore",
    BLOGS_SEVEN: "/blogs/8-things-to-keep-in-mind-while-purchasing-a-mens-suit"
}